services:
  - type: web
    name: imam-malik-chatbot
    env: python
    repo: https://github.com/Malaikakhattak69/Wisdom-of-Four
    branch: main
    rootDir: imam_malik_backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host=0.0.0.0 --port=10000
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free
